version: "2"
services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data/pgdata

  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_HOME=/etc/alternatives/jre_11/
    volumes:
      - ./jenkins:/var/jenkins_home

  sonarqube:
    image: sonarqube:community
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
